package maestrooso.projects.soap.rest.soapclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2019-02-13T15:18:26.831-05:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "TestResourceService",
                  wsdlLocation = "file:/G:/Avianca/Integraciones/rh-av-sapcurrency/src/main/resources/TestWsdl.wsdl",
                  targetNamespace = "http://www.peiky.com/payment")
public class TestResourceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.peiky.com/payment", "TestResourceService");
    public final static QName TestResourceSoap11 = new QName("http://www.peiky.com/payment", "TestResourceSoap11");
    static {
        URL url = null;
        try {
            url = new URL("file:/G:/Avianca/Integraciones/rh-av-sapcurrency/src/main/resources/TestWsdl.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TestResourceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/G:/Avianca/Integraciones/rh-av-sapcurrency/src/main/resources/TestWsdl.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TestResourceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TestResourceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestResourceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TestResourceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TestResourceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TestResourceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns TestResource
     */
    @WebEndpoint(name = "TestResourceSoap11")
    public TestResource getTestResourceSoap11() {
        return super.getPort(TestResourceSoap11, TestResource.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestResource
     */
    @WebEndpoint(name = "TestResourceSoap11")
    public TestResource getTestResourceSoap11(WebServiceFeature... features) {
        return super.getPort(TestResourceSoap11, TestResource.class, features);
    }

}
