package maestrooso.projects.soap.rest.payment;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2019-02-13T15:18:26.705-05:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://www.peiky.com/payment", name = "TestResource")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TestResource {

    @WebMethod(operationName = "UserLogin")
    @WebResult(name = "UserLoginResponse", targetNamespace = "http://www.peiky.com/payment", partName = "UserLoginResponse")
    public UserLoginResponse userLogin(
        @WebParam(partName = "UserLoginRequest", name = "UserLoginRequest", targetNamespace = "http://www.peiky.com/payment")
        UserLoginRequest userLoginRequest
    );

    @WebMethod(operationName = "MovementGetByUserCode")
    @WebResult(name = "MovementGetByUserCodeResponse", targetNamespace = "http://www.peiky.com/payment", partName = "MovementGetByUserCodeResponse")
    public MovementGetByUserCodeResponse movementGetByUserCode(
        @WebParam(partName = "MovementGetByUserCodeRequest", name = "MovementGetByUserCodeRequest", targetNamespace = "http://www.peiky.com/payment")
        MovementGetByUserCodeRequest movementGetByUserCodeRequest
    );

    @WebMethod(operationName = "MovementGetByCreditCardToken")
    @WebResult(name = "MovementGetByCreditCardTokenResponse", targetNamespace = "http://www.peiky.com/payment", partName = "MovementGetByCreditCardTokenResponse")
    public MovementGetByCreditCardTokenResponse movementGetByCreditCardToken(
        @WebParam(partName = "MovementGetByCreditCardTokenRequest", name = "MovementGetByCreditCardTokenRequest", targetNamespace = "http://www.peiky.com/payment")
        MovementGetByCreditCardTokenRequest movementGetByCreditCardTokenRequest
    );

    @WebMethod(operationName = "CreditCardGetByUserCode")
    @WebResult(name = "CreditCardGetByUserCodeResponse", targetNamespace = "http://www.peiky.com/payment", partName = "CreditCardGetByUserCodeResponse")
    public CreditCardGetByUserCodeResponse creditCardGetByUserCode(
        @WebParam(partName = "CreditCardGetByUserCodeRequest", name = "CreditCardGetByUserCodeRequest", targetNamespace = "http://www.peiky.com/payment")
        CreditCardGetByUserCodeRequest creditCardGetByUserCodeRequest
    );
}
